apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

nodes:
- role: control-plane

  # Allow ingress controller to run
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"

  # Map container ports to host
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP

